### ISSUE TITLE
Follow-up from #9

### ISSUE THREAD

**Issue by skwerlman** [Belethors-General-Mods/belethor#11]
- [x] Create new `common` app
  - [x] move `debug` logging macro into its own module (and maybe create analogs for other levels?)
  - [x] define types `Client.query()` and `Client.search_result()`
- [x] fix missed doc change https://github.com/Belethors-General-Mods/belethor/pull/9/files/32e5f85165de9f955d3276a50a15f8abe927d935#r238450387
- [x] make incorrect call to using a compile-time error; see https://github.com/Belethors-General-Mods/belethor/pull/9/files/32e5f85165de9f955d3276a50a15f8abe927d935#r238451507

**Comment by iggi42** [comment]
Erlang and Elixir use the British spelling, at least regarding behavior / behaviour.
I suggest we use it too then.

**Comment by iggi42** [comment]
also I got it to derivative from `__MODULE__` with the now obvious solution :100: (pr incoming)

**Comment by skwerlman** [comment]
this was fixed by #19
